[snackpub] better join/leave channel (#399)
# Why

remove the `fetchSockets` code which getting timeout occasionally.
```
Error: timeout reached while waiting for fetchSockets response at Timeout._onTimeout (/app/node_modules/@socket.io/redis-adapter/dist/index.js:559:28) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
```
close ENG-7773

(this should be the last one pr for us to test snackpub on production. there's still a server readiness check task and i'll do it after production testing).

# How

originally i used `fetchSockets` to get the socket's custom data - `deviceId` when `join-room`/`leave-room`.  the `fetchSockets` is not efficient and requires more expensive work for querying data from redis adapter. it turns out that we don't have to send the `joinChannel`/`leaveChannel` from `join-room`/`leave-room` time. we could do it at the exact timing:
  - when receiving the `subscribeChannel` command
  - when receiving the `unsubscribeChannel` command
  - if case client disconnects network without sending the `unsubscribeChannel` command, we should also broadcast `leaveChannel` when some clients get disconnected.

Co-authored-by: James Ide <ide@users.noreply.github.com>